# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
        args: ['--maxkb=60000']
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
    -   id: shellcheck
-   repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.28
    hooks:
    -   id: terragrunt-hclfmt # terragrunt hcl format files
-   repo: local
    hooks:
    -   id: terragrunt-hcl-validate
        name: Terragrunt HCL validate
        entry: bash ./hooks/terragrunt_hcl_validate.sh
        language: system
        types: [hcl]
        description: Run Terragrunt validate on changed files
        pass_filenames: true
    -   id: terragrunt-validate-inputs
        name: Terragrunt validate inputs
        entry: bash ./hooks/terragrunt_validate_inputs.sh
        language: system
        types: [hcl]
        description: Run Terragrunt validate on changed files
        pass_filenames: true
