name: Terragrunt

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  terragrunt:
    name: 'Terragrunt'
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Step to install necessary dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip direnv

      # Step to setup the repository
      - name: Setup Repository
        run: |
          SKIP=enable_pre_commit ./bootstrap.sh

          # Extract the updated PATH and write it to GITHUB_ENV
          NEW_PATH=$(direnv exec . bash -c 'echo $PATH')
          echo "PATH=$NEW_PATH" >> $GITHUB_ENV

      # Determine the working directory based on the branch name
      - name: Set Working Directory
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "WORKING_DIR=prod" >> $GITHUB_ENV
          else
            echo "WORKING_DIR=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Terragrunt Init
        run: terragrunt run-all init --non-interactive
        working-directory: ./live/${{ env.WORKING_DIR }}

      - name: Terragrunt Plan
        run: terragrunt run-all plan --non-interactive
        working-directory: ./live/${{ env.WORKING_DIR }}

      - name: Terragrunt Apply
        run: terragrunt run-all apply --non-interactive
        working-directory: ./live/${{ env.WORKING_DIR }}
