name: Terragrunt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terragrunt:
    name: 'Terragrunt'
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Step to install necessary dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip direnv

      # Step to setup the repository
      - name: Setup Repository
        run: |
          SKIP=enable_pre_commit ./bootstrap.sh
          ls -lrt bin/

          # Extract the updated PATH and write it to GITHUB_ENV
          NEW_PATH=$(direnv exec . bash -c 'echo $PATH')
          echo "PATH=$NEW_PATH" >> $GITHUB_ENV

      - name: Terragrunt Init
        run: terragrunt run-all init --non-interactive
        working-directory: ./live/prod

      - name: Terragrunt Plan
        run: terragrunt run-all plan --non-interactive
        working-directory: ./live/prod

      - name: Terragrunt Apply
        run: terragrunt run-all apply --non-interactive
        working-directory: ./live/prod
