name: Terragrunt Apply
# This workflow is triggered when a pull request is closed.
# It checks for modified files in the working directory and apply terragrunt.

on:
  pull_request:
    branches:
      - dev
      - main
    types:
      - closed

jobs:
  terragrunt_set_environment:
    name: Set Environment
    if: github.event.pull_request.merged == true
    uses: zcode-ia/gitops-workflows/.github/workflows/terragrunt-set-environment.yml@main
    with:
      github_base_ref: ${{ github.base_ref }}

  github_list_pr_files:
    name: List Modified Files
    if: github.event.pull_request.merged == true
    uses: zcode-ia/gitops-workflows/.github/workflows/github-list-pr-files.yml@main
    with:
      github_repository: ${{ github.repository }}
      github_event_pull_request_number: ${{ github.event.pull_request.number }}
    secrets:
      github_secret_token: ${{ secrets.GITHUB_TOKEN }}

  terragrunt_filter_working_dir:
    name: Filter Working Directory
    needs:
      - terragrunt_set_environment
      - github_list_pr_files
    if: github.event.pull_request.merged == true && needs.github_list_pr_files.outputs.pr_files_count > 0
    uses: zcode-ia/gitops-workflows/.github/workflows/terragrunt-filter-working-dir.yml@main
    with:
      working_directory_filter: ${{ needs.terragrunt_set_environment.outputs.working_dir }}
      encoded_modified_files_to_filter: ${{ needs.github_list_pr_files.outputs.encoded_modified_files }}

  terragrunt_apply:
    name: Terragrunt Apply
    needs: terragrunt_filter_working_dir
    if: needs.terragrunt_filter_working_dir.outputs.working_dirs_count > 0
    uses: zcode-ia/gitops-workflows/.github/workflows/terragrunt-apply.yml@main
    with:
      encoded_working_dirs: ${{ needs.terragrunt_filter_working_dir.outputs.encoded_working_dirs }}
      github_workspace: ${{ github.workspace }}
      github_run_id: ${{ github.run_id }}
      github_event_pull_request_number: ${{ github.event.pull_request.number }}

  github_post_comment:
    name: Github Post Comment
    needs:
      - terragrunt_filter_working_dir
      - terragrunt_apply
    if: needs.terragrunt_filter_working_dir.outputs.working_dirs_count > 0
    uses: zcode-ia/gitops-workflows/.github/workflows/github-post-comment.yml@main
    with:
      github_repository: ${{ github.repository }}
      github_event_pull_request_number: ${{ github.event.pull_request.number }}
      encoded_comment_title: ${{ needs.terragrunt_apply.outputs.encoded_comment_title }}
      encoded_comment_outputs: ${{ needs.terragrunt_apply.outputs.encoded_comment_outputs }}
      artifact_id: ${{ needs.terragrunt_apply.outputs.artifact_id }}
      artifact_url: ${{ needs.terragrunt_apply.outputs.artifact_url }}
    secrets:
      github_secret_token: ${{ secrets.GITHUB_TOKEN }}

  check_workflow_status:
    name: Check Workflow Status
    needs:
      - terragrunt_filter_working_dir
      - terragrunt_apply
    if: needs.terragrunt_filter_working_dir.outputs.working_dirs_count > 0
    uses: zcode-ia/gitops-workflows/.github/workflows/github-check-workflow-status.yml@main
    with:
      main_outcome: ${{ needs.terragrunt_apply.outputs.main_outcome }}
